name: periscope_multifasta
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - tqdm
  - plotnine
  - pandas
  - samtools
  - numpy
  - pysam
  - minimap2
  - bwa
  - bedtools
  - biopython
  - pybedtools
  - snakemake-minimal
  - pytest
  - pip
  - setuptools
  - pyvcf
  - bcbio-gff
  - pip:
    - git+https://github.com/artic-network/fieldbioinformatics.git@1.1.1
