threads = config.get("mapping_threads")
split_suffix = [f"{i+1:04}" for i in range(int(threads))]

wildcard_constraints:
    output_prefix="|".join([config.get("output_prefix")]),
    split_suffix='|'.join(split_suffix),

rule all:
    input:
        expand("{output_prefix}.bam", output_prefix=config.get("output_prefix")),
        expand("{output_prefix}.bam.bai", output_prefix=config.get("output_prefix")),
        expand("{output_prefix}_periscope_counts.csv", output_prefix=config.get("output_prefix")),
        expand("{output_prefix}_periscope_novel_counts.csv", output_prefix=config.get("output_prefix")),
        expand("{output_prefix}_periscope_amplicons.csv", output_prefix=config.get("output_prefix")),

########################################
# ALIGN
########################################

if config["technology"] == "illumina":

    rule align:
        input:
            fastq=config.get("fastq")
        output:
            "{output_prefix}.bam"
        params:
            reference=f"{config.get('resources_dir')}/{config.get('reference_fasta')}",
            threads=config.get("mapping_threads")
        shell:
            "bwa mem -Y -t {params.threads} {params.reference} {input.fastq} | samtools sort - | samtools view -bh - > {output}"

elif config["technology"] == "ont":

    if config.get('fastq_dir'):
        if config.get('gzipped'):

            rule collect_fastqs:
                output:
                    f"{{output_prefix}}.{config.get('extension')}"
                params:
                    fastq_dir=config.get("fastq_dir"),
                    extension=config.get("extension")
                shell:
                    "zcat {params.fastq_dir}/*.{params.extension} > {output}"

        else:

            rule collect_fastqs:
                output:
                    f"{{output_prefix}}.{config.get('extension')}"
                params:
                    fastq_dir=config.get("fastq_dir"),
                    extension=config.get("extension")
                shell:
                    "cat {params.fastq_dir}/*.{params.extension} > {output}"

        rule align:
            input:
                merged_fastq=f"{{output_prefix}}.{config.get('extension')}"
            output:
                "{output_prefix}.bam"
            params:
                reference=f"{config.get('resources_dir')}/{config.get('reference_fasta')}",
                threads=config.get("mapping_threads")
            shell:
                "minimap2 -ax map-ont -k 15 -t {params.threads} {params.reference} {input.merged_fastq} | samtools sort - | samtools view -bh - > {output}"

    else:
        rule align:
            input:
                fastq=config.get("fastq")
            output:
                "{output_prefix}.bam"
            params:
                reference=f"{config.get('resources_dir')}/{config.get('reference_fasta')}",
                threads=config.get("mapping_threads")
            shell:
                "minimap2 -ax map-ont -k 15 -t {params.threads} {params.reference} {input.fastq} | samtools sort - | samtools view -bh - > {output}"

########################################
# INDEX
########################################

rule index:
    input:
        bam="{output_prefix}.bam"
    output:
        "{output_prefix}.bam.bai"
    shell:
        "samtools index {input.bam}"

########################################
# BAM → SAM
########################################

rule bam_to_sam:
    input:
        bam="{output_prefix}.bam"
    output:
        sam="{output_prefix}.sam"
    shell:
        "samtools view -h {input.bam} > {output.sam}"

########################################
# PERISCOPE
########################################

rule periscope:
    input:
        sam="{output_prefix}.sam",
        bam="{output_prefix}.bam",
        bai="{output_prefix}.bam.bai"
    output:
        "{output_prefix}_periscope_counts.csv",
        "{output_prefix}_periscope_amplicons.csv",
        "{output_prefix}_periscope_novel_counts.csv"
    params:
        prefix=f"{config.get('output_prefix')}_split",
        search=f"{config.get('scripts_dir')}/search_for_sgRNA_{config.get('technology')}.py",
        output_prefix=config.get("output_prefix"),
        score_cutoff=config.get("score_cutoff"),
        sample=config.get("sample"),
        orf_bed=f"{config.get('resources_dir')}/{config.get('orf_bed')}",
        primer_bed=config.get("primer_bed"),
        amplicon_bed=config.get("amplicon_bed"),
        tmp=config.get("tmp"),
        threads=config.get("threads")
    run:
        # Picard split (outputs multiple BAMs)
        shell("""
        picard SplitSamByNumberOfReads \
            -I {input.sam} \
            -N_FILES {params.threads} \
            -O . \
            --OUT_PREFIX {params.prefix}
        """)

        # mark split outputs as temp so Snakemake deletes them
        import glob
        split_files = glob.glob(f"{params.prefix}_*.bam")
        for f in split_files:
            temp(f)

        shell("""
        python {params.search} \
            --bam {input.bam} \
            --score-cutoff {params.score_cutoff} \
            --output-prefix {params.output_prefix} \
            --sample {params.sample} \
            --orf-bed {params.orf_bed} \
            --primer-bed {params.primer_bed} \
            --amplicon-bed {params.amplicon_bed} \
            --tmp {params.tmp} \
            --threads {params.threads}
        """)
